name: Build e Deploy da Visualiza API

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build e Push da Imagem Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Define o SHA como tag
        id: vars
        run: echo "sha_tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build -t rafaelaheer/visualiza-api:latest -t rafaelaheer/visualiza-api:${{ env.sha_tag }} .

      - name: Push da imagem com tag `latest` e SHA
        run: |
          docker push rafaelaheer/visualiza-api:latest
          docker push rafaelaheer/visualiza-api:${{ env.sha_tag }}
